name: SideBar
main: com.empcraft.sidebar.SideBar
version: 0.1.3
author: Empire92
website: www.empcraft.com
softdepend: [IndividualMessages,Factions,EnjinMinecraftPlugin,Essentials,Vault]
depend: []
commands:
   sidebar:
      description: SideBar commands;
   sb:
      description: SideBar commands;